### Recuperar todas las peliculas
GET http://localhost:3000/movies

### Recuperar una pelicula por id
GET http://localhost:3000/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Recuperar todas las peliculas por un genero
GET http://localhost:3000/movies?genre=action



### Crear pelicula
POST http://localhost:3000/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
 

}

###
PATCH http://localhost:3000/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf
Content-Type: application/json

{
  "year": 2014,
  "rate": 10
}


### Eliminar Pelicula
DELETE http://localhost:3000/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf
